### ISSUE TITLE
Token question + documentation suggestion

### ISSUE THREAD

**Issue by dopeboy** [useparcel/vercel-is-pull-request#2]
First off, this is _tremendously_ helpful - thank you @avigoldman. 

A question and a suggestion:

1. Do I have to create a personal access token to get this working? I assume when github sends a webhook to vercel upon deploy, there's some token baked in there to clone a private repository. Is there a way to re-use that rather than have to create a new token? I tried `GITHUB_TOKEN` and all permutations of it, no luck. So as of now, I have a long lasting PAT hardcoded into my vercel dashboard - which I'm not too thrilled about.

2. The additional environment variables you surface are only available at build time. I need to know these values at run time. So I needed to perform the additional step of adding the below to my `next.config.js` file. Maybe worth adding to the README? Happy to volunteer for a PR.

```
module.exports = {
    .
    .
    .
    env: {
        VERCEL_GIT_PULL_REQUEST_NUMBER: process.env.VERCEL_GIT_PULL_REQUEST_NUMBER,
    },
}
```

**Comment by avigoldman** [comment]
Glad to hear it!

1. I only got it working with the personal token. If you can get with without that I'd love to switch it as well.
2. Would love to have a PR with that documentation.

**Comment by avigoldman** [comment]
Vercel has added a native variable for this now so I'm deprecating this CLI

https://github.com/vercel/vercel/discussions/5479#discussioncomment-5548062
