### ISSUE TITLE
Script not found

### ISSUE THREAD

**Issue by JClackett** [useparcel/vercel-is-pull-request#3]
Hey, appreciate this package, but for some reason I get this when building:

```
Running "source node_modules/.bin/vercel-is-pull-request && next build"
--
14:35:03.706 | sh: node_modules/.bin/vercel-is-pull-request: No such file or directory
14:35:03.720 | Error: Command "source node_modules/.bin/vercel-is-pull-request && next build" exited with 1
```

I am running next.js in a monorepo but I've tried adding this package to the root node_modules and the one that's inside the nextjs app package. any ideas?

**Comment by JClackett** [comment]
Think I figured it, needed to add noHoist so that the package is in the nextjs node_modules

**Comment by laneschmidt** [comment]
@JClackett hey i'm facing a similar issue, just wondering if this is more or less what you did?

```
// monorepo root package.json

"workspaces": {
    "packages": [
      "apps/*",
      "packages/*"
    ],
    "nohoist": [
      "**/vercel-is-pull-request",
      "**/vercel-is-pull-request/**"
    ]
  },
```

the above doesn't seem to do the trick, so i figure i'm implementing it wrong. thank you

**Comment by JClackett** [comment]
Yeah that should be fine, is your next build script like this?

```sh
source node_modules/.bin/vercel-is-pull-request --auth <app-token> && next build
```
