### ISSUE TITLE
pnpm monorepo

### ISSUE THREAD

**Issue by JClackett** [useparcel/vercel-is-pull-request#5]
Any ideas how to get this running in a pnpm monorepo?

the generated bin script in node_modules can never seem to find the cmd.sh file, ive tried hoisting, and not, but it can never find it

```
/bin/sh: ./../vercel-is-pull-request/cmd.sh: No such file or directory
```

**Comment by avigoldman** [comment]
Vercel has added an native variable for this now!

https://github.com/vercel/vercel/discussions/5479#discussioncomment-5548062
